// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRxfyfxOXQ0aToWF0YdB3ZMeCVoxYw0VI',
    appId: '1:742494272733:web:9ccf31822e7643fa69af34',
    messagingSenderId: '742494272733',
    projectId: 'taskmanager6',
    authDomain: 'taskmanager6.firebaseapp.com',
    storageBucket: 'taskmanager6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjfxqczXGfkltEAvRAau_6XBnt5B2Pfu8',
    appId: '1:742494272733:android:6a4117d0c0ac560e69af34',
    messagingSenderId: '742494272733',
    projectId: 'taskmanager6',
    storageBucket: 'taskmanager6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO8_jCkMWGk1FUlHgmPzlymtkocgAYpGc',
    appId: '1:742494272733:ios:d9bdedf756dc9b5669af34',
    messagingSenderId: '742494272733',
    projectId: 'taskmanager6',
    storageBucket: 'taskmanager6.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO8_jCkMWGk1FUlHgmPzlymtkocgAYpGc',
    appId: '1:742494272733:ios:d9bdedf756dc9b5669af34',
    messagingSenderId: '742494272733',
    projectId: 'taskmanager6',
    storageBucket: 'taskmanager6.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRxfyfxOXQ0aToWF0YdB3ZMeCVoxYw0VI',
    appId: '1:742494272733:web:17a229ab3fea1bbe69af34',
    messagingSenderId: '742494272733',
    projectId: 'taskmanager6',
    authDomain: 'taskmanager6.firebaseapp.com',
    storageBucket: 'taskmanager6.firebasestorage.app',
  );

}